site_title = "MyArxiv"
limit_days = 7
cache_url = "https://JIN-strong.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.DB"
title = "Databases"

[[sources]]
limit = 150
category = "cs.DC"
title = "Distributed, Parallel, and Cluster Computing"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"

